SSS-StoreStockSystem/ViewModels/StockViewModel.cs
namespace SSS_StoreStockSystem.ViewModels
{
    public class StockViewModel
    {
        public int StoreId { get; set; }
        public int ItemId { get; set; }
        public string StoreName { get; set; }
        public string ItemName { get; set; }
        public string StoreCode { get; set; }
        public string ItemCode { get; set; }
        public int Quantity { get; set; }


    }
}

SSS-StoreStockSystem/Controllers/StockController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata;
using SSS_StoreStockSystem.BLL.Interfaces;
using SSS_StoreStockSystem.BLL.UnitOfWork;
using SSS_StoreStockSystem.DAL.Models;
using SSS_StoreStockSystem.ViewModels;

namespace SSS_StoreStockSystem.Controllers
{
    public class StockController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IStockRepository _stockRepository;


        public StockController(IMapper mapper, IStockRepository stockRepository)
        {
            _mapper = mapper;
            _stockRepository = stockRepository;
        }
        public IActionResult Index()
        {
            var stock = _stockRepository.GetAll().ToArray();
            var mappedStock = _mapper.Map<StockViewModel[]>(stock);
            return View(mappedStock);
        }
        public IActionResult Alter()
        {
            var stock = _stockRepository.GetAll().ToArray();
            var mappedStock = _mapper.Map<StockViewModel[]>(stock);
            return View(mappedStock);
        }
        [HttpPost]
        public IActionResult Alter(string process, int advancedQuantity, int storeId, int itemId)
        {
            if (storeId == 0 && itemId == 0)
                return RedirectToAction(nameof(Index), TempData["Message"] = "Invalid Entry");
            if (advancedQuantity <= 0)
                return RedirectToAction(nameof(Index), TempData["Message"] = "Invalid Quantity");
            var storeItem = _stockRepository.Fetch(itemId, storeId);
            if (process == "buy")
            {
                if (storeItem == null)
                {
                    storeItem = new StoreItem
                    {
                        ItemId = itemId,
                        StoreId = storeId,
                        Quantity = advancedQuantity
                    };
                    _stockRepository.Insert(storeItem);
                    _stockRepository.Log("buy", advancedQuantity, 0, storeId, itemId);
                }
                else
                {
                    storeItem.Quantity = storeItem.Quantity + advancedQuantity;
                    _stockRepository.Alter(storeItem);
                    _stockRepository.Log("buy", storeItem.Quantity, storeItem.Quantity - advancedQuantity, storeId, itemId);
                }
            }
            else if (process == "sell")
            {
                if (storeItem == null)
                    return RedirectToAction(nameof(Index), TempData["Message"] = "Not Enough Quantity");
                
                storeItem.Quantity = storeItem.Quantity - advancedQuantity;
                if (storeItem.Quantity <= 0)
                {
                    _stockRepository.CleanUp(storeItem);
                    _stockRepository.Log("sell", 0, storeItem.Quantity + advancedQuantity, storeId, itemId);
                }
                else
                {
                    _stockRepository.Alter(storeItem);
                    _stockRepository.Log("sell", storeItem.Quantity, storeItem.Quantity + advancedQuantity, storeId, itemId);
                }
            }
            _stockRepository.Save();
            return View();
        }
        public int GetQuantity(int storeId, int itemId)
        {
            if (storeId == 0 )
            {
                return _stockRepository.GetAll().Where(x => x.ItemId == itemId).Sum(x => x.Quantity);
            }
            if (itemId == 0)
            {
                return 0;
            }
            var stock = _stockRepository.Fetch(itemId, storeId);
            return stock == null ? 0 : stock.Quantity;
        }
    }
}

SSS-StoreStockSystem/Views/Stock/Alter.cshtml
@using SSS_StoreStockSystem.BLL.Interfaces
@model IEnumerable<StockViewModel>
@inject IStockRepository _stockRepository
@{
    ViewData["Title"] = "Alter";
    ViewData["Stores"] = _stockRepository.GetStores();
    ViewData["Items"] = _stockRepository.GetItems();

}

<h1 class="m-5">Alter Stock <i class="fa-solid fa-file-invoice-dollar"></i> </h1>
<form asp-action="Alter" method="post">
    <div class="form-group w-50 m-4">
    <label value="Store" class=" control-label col-form-label"></label>
        <select id="store-select" name="StoreId" class="trigger-select form-control form-select-lg">
        <option>All Stores</option>
        @foreach (var item in ViewData["Stores"] as IEnumerable<Store>)
        {
            <option value="@item.Id">@item.Name - @item.Code</option>
        }
    </select>
</div>
    <div class="form-group w-50 m-4">
    <label value="Items" class="control-label col-form-label"></label>
        <select id="item-select" name="itemId" class="trigger-select form-control form-select-lg">
        <option> None </option>
        @foreach (var item in ViewData["Items"] as IEnumerable<Item>)
        {
            <option value="@item.Id">@item.Name - @item.Code</option>
        }
    </select>
    </div>
    <div class="form-outline w-50 m-4" data-mdb-input-init>
        <input class="form-control form-control-lg"
               id="formControlReadonly"
               type="text"
               value=" "
               aria-label="readonly input example"
               readonly />
        <label class="form-label" for="formControlReadonly">Current Quantity</label>
    </div>
    <div class="input-group w-50 m-4">
        <input type="text"
               class="form-control form-control-lg"
               placeholder="Enter Quantity"
               aria-label="Recipient's username with two button addons"
               name="advancedQuantity"/>
        <button class="btn btn-outline-success" name ="process" value="buy" type="submit" data-mdb-ripple-init data-mdb-ripple-color="dark">
            Buy
        </button>
        <button class="btn btn-outline-danger" name="process" value="sell" type="submit" data-mdb-ripple-init data-mdb-ripple-color="dark">
            Sell
        </button>
    </div>
</form>
<div class="h-100 d-flex flex-row justify-content-end align-items-end">
    <a asp-controller="Stock" asp-action="Index" mdbRipple data-mdb-ripple-init class="btn btn-outline-primary btn-lg m-2"> <i class="fa-regular fa-hand-point-left"></i> Back To Stock Items</a>
</div>
<script>
    @section Scripts
    {
        <script>
            $(document).ready(function () {
            $(".trigger-select").change(function () {
                var selectedStore = $("#store-select").children("option:selected").val();
                var selectedItem = $("#item-select").children("option:selected").val();
                $.ajax({
                    url: "/Stock/GetQuantity",
                    type: "GET",
                    data: { storeId: selectedStore, itemId: selectedItem },
                    success: function (data) {
                        $("#formControlReadonly").val(data);
                    }
                });
            });
        });
        </script>
        }
</script>

SSS-StoreStockSystem/Views/Stock/Index.cshtml
@model IEnumerable<StockViewModel>

@{
    ViewData["Title"] = "Index";
}
<h1 class="m-5">Stock <i class="fa-solid fa-list-check"></i></h1>
@if (Model.Count() > 0)
{
    <div class="table-responsive m-0">
        <table class="table table-hover border-danger">
            <thead>
                <tr>
                    <th scope="col">Store Code</th>
                    <th scope="col">Store Name</th>
                    <th scope="col">Item Code</th>
                    <th scope="col">Item Name</th>
                    <th scope="col">Current Quantity</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var stock in Model)
                {
                    <tr>
                        <th scope="row">@stock.StoreCode</th>
                        <td>@stock.StoreName</td>
                        <td>@stock.ItemCode</td>
                        <td>@stock.ItemName</td>
                        <td>@stock.Quantity</td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
    <div class="h-100 d-flex flex-row justify-content-end align-items-end">
        <a mdbRipple data-mdb-ripple-init asp-controller="Stock" asp-action="Alter" class="btn btn-primary m-5 btn-lg"> <i class="fa-solid fa-pencil"></i> Alter Stock</a>
    </div>
}
else
{
    <div class="alert alert-primary fade show m-5" id="alertExample" role="alert" data-mdb-color="secondary">
        <i class="fas fa-store-slash"></i>
        There's No Stock Found in the Database
        <a asp-controller="Stock" asp-action="Alter" class="alert-link me-1">Alter Stock!</a>
    </div>
}
@if (TempData["Message"] != null)
{
    <div class="alert alert-danger mb-0 alert-dismissible alert-absolute fade show" id="alertExample" role="alert" data-mdb-color="secondary">

        @TempData["Message"]

        <button type="button" class="btn-close ms-2" data-mdb-dismiss="alert" aria-label="Close"></button>
    </div>
}