SSS-StoreStockSystem/ViewModels/StoreViewModel.cs
using SSS_StoreStockSystem.DAL.Models;
using System.ComponentModel.DataAnnotations;

namespace SSS_StoreStockSystem.ViewModels
{
    public class StoreViewModel
    {
        public int Id { get; set; }

        [MaxLength(7)]
        [MinLength(7)]
        [Required]
        [RegularExpression(@"^[A-Za-z]{3}-\d{3}$", ErrorMessage = "Code must be in the format of three letters, a hyphen, and three numbers.")]
        public string Code { get; set; }

        [MaxLength(100)]
        [MinLength(2)]
        [Required]
        public string Name { get; set; }

        [MaxLength(100)]
        [MinLength(2)]
        public string? Location { get; set; }

        public IFormFile Image { get; set; }
        public string ImageName { get; set; }

        public ICollection<StoreItem> StoreItems { get; } = new HashSet<StoreItem>();
    }
}

SSS-StoreStockSystem/Controllers/ItemController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SSS_StoreStockSystem.BLL.UnitOfWork;
using SSS_StoreStockSystem.DAL.Models;
using SSS_StoreStockSystem.Helpers;
using SSS_StoreStockSystem.ViewModels;


namespace SSS_ItemStockSystem.Controllers
{
    public class ItemController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;


        public ItemController(IMapper mapper, IUnitOfWork unitOfWork)
        {
            _mapper = mapper;
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var items = _unitOfWork.ItemRepository.GetAll().ToArray();
            var mappedItems = _mapper.Map<Item[], ItemViewModel[]>(items);
            return View(mappedItems);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(ItemViewModel itemVM)
        {
            itemVM.ImageName = DocumentSettings.UploadFile(itemVM.Image, "images");
            var item = _mapper.Map<Item>(itemVM);
            _unitOfWork.ItemRepository.Add(item);
            var count = _unitOfWork.Complete();
            if (count > 0)
            {
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (!id.HasValue)
            {
                return BadRequest();
            }
            var item = _unitOfWork.ItemRepository.GetById(id.Value);
            if (item == null)
            {
                return NotFound();
            }
            var mappedItem = _mapper.Map<ItemViewModel>(item);
            return View(mappedItem);

        }
        [HttpPost]
        public IActionResult Edit(ItemViewModel itemVM)
        {
            if (itemVM.Image != null)
            {
                DocumentSettings.DeleteFile(itemVM.ImageName, "images");
                itemVM.ImageName = DocumentSettings.UploadFile(itemVM.Image, "images");
            }
            var mappedItem = _mapper.Map<Item>(itemVM);
            try
            {
                _unitOfWork.ItemRepository.Update(mappedItem);
                var count = _unitOfWork.Complete();
                if (count > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }

            return View(mappedItem);
        }
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (!id.HasValue)
            {
                return BadRequest();
            }
            var item = _unitOfWork.ItemRepository.GetById(id.Value);
            if (item == null)
            {
                return NotFound();
            }
            try
            {
                item.IsDeleted = true;
                _unitOfWork.ItemRepository.Update(item);
                var count = _unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                TempData["Error"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }


        }
    }
}

SSS-StoreStockSystem/Controllers/StoreController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using SSS_StoreStockSystem.BLL.Interfaces;
using SSS_StoreStockSystem.BLL.Repositories;
using SSS_StoreStockSystem.BLL.UnitOfWork;
using SSS_StoreStockSystem.DAL.Data;
using SSS_StoreStockSystem.DAL.Models;
using SSS_StoreStockSystem.Helpers;
using SSS_StoreStockSystem.ViewModels;
using System.Reflection.Metadata;

namespace SSS_StoreStockSystem.Controllers
{
    public class StoreController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;


        public StoreController(IMapper mapper, IUnitOfWork unitOfWork)
        {
            _mapper = mapper;
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var stores = _unitOfWork.StoreRepository.GetAll().ToArray();
            var mappedStores = _mapper.Map<Store[], StoreViewModel[]>(stores);
            return View(mappedStores);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(StoreViewModel storeVM)
        {
            storeVM.ImageName = DocumentSettings.UploadFile(storeVM.Image, "images");
            var store = _mapper.Map<Store>(storeVM);
            _unitOfWork.StoreRepository.Add(store);
            var count = _unitOfWork.Complete();
            if (count > 0)
            {
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (!id.HasValue)
            {
                return BadRequest();
            }
            var store = _unitOfWork.StoreRepository.GetById(id.Value);
            if (store == null)
            {
                return NotFound();
            }
            var mappedStore = _mapper.Map<StoreViewModel>(store);
            return View(mappedStore);

        }
        [HttpPost]
        public IActionResult Edit(StoreViewModel storeVM) 
        {
            if (storeVM.Image != null)
            {
                DocumentSettings.DeleteFile(storeVM.ImageName, "images");
                storeVM.ImageName = DocumentSettings.UploadFile(storeVM.Image, "images");
            }
            var mappedStore = _mapper.Map<Store>(storeVM);
            try
            {
                _unitOfWork.StoreRepository.Update(mappedStore);
                var count = _unitOfWork.Complete();
                if (count > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }

            return View(mappedStore);
        }
        [HttpGet]
        public IActionResult Delete(int? id) 
        {
            if (!id.HasValue)
            {
                return BadRequest();
            }
            var store = _unitOfWork.StoreRepository.GetById(id.Value);
            if (store == null)
            {
                return NotFound();
            }
            try
            {
                store.IsDeleted = true;
                _unitOfWork.StoreRepository.Update(store);
                var count = _unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                TempData["Error"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }

          
        }
    }
}

SSS-StoreStockSystem/Views/Store/Create.cshtml
@model StoreViewModel
@{
    ViewData["Title"] = "Create";
}

<h1 class="m-5">Add New Store <i class="fa-solid fa-shop"></i> </h1>
<form action="/Store/Create" method="post" enctype="multipart/form-data">

    <partial name="PartialViews/CreateEditStorePartial" />

    <div class="h-100 d-flex flex-row justify-content-end align-items-end">
        <button mdbRipple data-mdb-ripple-init type="submit" class="btn btn-success btn-lg m-2"> <i class="fa-solid fa-check"></i> Add Store </button>
    </div>
    <div class="h-100 d-flex flex-row justify-content-end align-items-end">
        <a asp-controller="Store" asp-action="index" mdbRipple data-mdb-ripple-init class="btn btn-outline-success btn-lg m-2"> <i class="fa-solid fa-angles-left"></i> Back To Stores </a>
    </div>
    </form>
@section ValidationScriptSection
{
<partial name="_ValidationScriptsPartial" />
}

SSS-StoreStockSystem/Views/Store/Edit.cshtml
@model StoreViewModel
@{
    ViewData["Title"] = "Edit";
}

<h1 class="m-5">Edit Store <i class="fa-solid fa-shop"></i> </h1>
<form asp-action="Edit" method="post" enctype="multipart/form-data">

    <partial name="PartialViews/CreateEditStorePartial" />

    <div class="h-100 d-flex flex-row justify-content-end align-items-end">
        <button mdbRipple data-mdb-ripple-init type="submit" class="btn btn-success btn-lg m-2"> <i class="fa-solid fa-check"></i> Edit Store </button>
    </div>
    <div class="h-100 d-flex flex-row justify-content-end align-items-end">
        <a asp-controller="Item" asp-action="index" mdbRipple data-mdb-ripple-init class="btn btn-outline-success btn-lg m-2"> <i class="fa-solid fa-angles-left"></i> Back To Stores </a>
    </div>
    <input type="hidden" asp-for="ImageName" />
</form>
@section ValidationScriptSection {
    <partial name="_ValidationScriptsPartial" />
}

SSS-StoreStockSystem/Views/Store/Index.cshtml
@model IEnumerable<StoreViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1 class="m-5">Stores <i class="fas fa-store"></i></h1>

@if(Model.Count() > 0)
{
    <div class="table-responsive m-0">
        <table class="table table-hover table-light border-primary">
            <thead>
                <tr>
                    <th scope="col">Code</th>
                    <th scope="col">Image</th>
                    <th scope="col">Name</th>
                    <th scope="col">Location</th>
                    <th scope="col">Operations</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var store in Model)
                {
                    <tr>
                     <th scope="row">@store.Code</th>
                    <td><img src="~/files/images/@store.ImageName" style="width:100px"></td>
                    <td>@store.Name</td>
                    <td>@store.Location</td>
                    <td>
                    <a mdbRipple data-mdb-ripple-init asp-controller="Store" asp-action="Edit" asp-route-id="@store.Id" class="btn btn-info m-2"> <i class="far fa-pen-to-square"></i> Edit Store</a>
                    <a mdbRipple data-mdb-ripple-init asp-controller="Store" asp-action="Delete" asp-route-id="@store.Id" class="btn btn-danger m-2"> <i class="far fa-trash-can"></i> Delete Store</a>
                    </td>
                </tr>
                }
            </tbody>

        </table>
    </div>
    <div class="h-100 d-flex flex-row justify-content-end align-items-end">
        <a mdbRipple data-mdb-ripple-init asp-controller="Store" asp-action="Create" class="btn btn-primary m-5 btn-lg"> <i class="far fa-square-plus"></i> Add New Store</a>

    </div>
}
else
{
    <div class="alert alert-primary mb-0 fade show m-5" id="alertExample" role="alert" data-mdb-color="secondary">
        <i class="fas fa-store-slash"></i>
        There's No Stores Found in the Database
        <a asp-controller="Store" asp-action="Create" class="alert-link me-1">Add Store!</a>
    </div>
}
@if (TempData["Message"] != null)
{
    <div class="alert alert-primary alert-dismissible alert-absolute fade show m-5" id="alertExample" role="alert" data-mdb-color="secondary">
        <i class="fas fa-check"></i>
        @TempData["Message"]
        <button type="button" class="btn-close ms-2" data-mdb-dismiss="alert" aria-label="Close"></button>
    </div>
}